### ISSUE TITLE
No default constructor for thrift types

### ISSUE THREAD

**Issue by mishadoff** [xsc/thrift-clj#8]
Assuming I have a simple thrift struct

```
struct A {
 1: string a;
 2: i32 b;
} 
```

Generated class `A.java` have default constructor, but if I use `(thrift/import (:types [A]))`
no default constructor is available.

Though, it may be a useful as a restriction but prevent common way to fill java structure:

```
(doto (A.)
  (.setA "some)
  (.setB 42))
```

**Comment by xsc** [comment]
This would indeed be the Java way of instantiating that value but thrift-clj's goal is to provide a more Clojure-y feel, e.g.

```clojure
(-> (map->A {})
    (assoc :a "some")
    (assoc :b 42))
```

You can then use `thrift-clj.core/->thrift` to generate the Thrift object. (And if you really want to use the Java way, just `import` the Thrift classes directly, without `thrift-clj`.)
